### ISSUE TITLE
Patch to openerp/netsvc.py

### ISSUE THREAD

**Issue by bwrsandman** [alainivars/openerp-sentry#3]
Thought I'd share what we're using to intercept OpenERP exceptions and sending them to sentry.

https://gist.github.com/bwrsandman/8117236

We add library versions from the included eggs from our buildout recipe.
We tag OSs and try to tag bzr revision numbers for openobject-addons/server

We hide the error from the user, while still showing it in the log.

If raven happens to fail during setup or capture, it does so silently and the regular behaviour runs.

We don't log AccessError (user doesn't have the rights to do something), Access Denied (user types a wrong password) or Warnings.

The patch is applied during our buildout.

**Comment by alainivars** [comment]
I agree, you are right, but for now I have just give what we are using in internal, I'm working to clean that step by change the lot of add in the file openerp/netsvc.py by the insertion of only one import (the path of the decorator) and a décorator inplemented in the plugin source.
